# -*- mode: python; python-indent-offset: 4; indent-tabs-mode: nil -*-
import os
env = Environment(tools = ['default', 'textfile'])

program_name = "main"
config_h_file = 'config.h'
config_h_in_file = config_h_file + '.in'
config_dict = {'@prefix@': '"/bin"'}

env.Substfile(config_h_in_file, SUBST_DICT = config_dict)

program_sources = [ 
    program_name + ".c",
]

env.Program(program_name, program_sources)
