# YAML -*- mode: yaml; tab-width: 2; indent-tabs-mode: nil; coding: utf-8 -*-
---

name: test

on:  # yamllint disable-line rule:truthy
  workflow_run:
    workflows: ["build"]
    types:
      - completed
run-name: "test: ${{ github.event.workflow_run.head_branch }}#${{ github.event.workflow_run.head_commit.id }}"
jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_commit.id }}
      - id: describe
        name: Describe HEAD
        run: >-
          echo "describe=$(git describe --tags --always || echo 0)"
          | tee $GITHUB_OUTPUT
